on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3
      - uses: actions/checkout@v2
      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.TOKEN }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=t2.micro \
          --labels=cml-runner
          
          
  test_and_deploy:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    steps:
    - uses: actions/checkout@v2
    - name: "tests"
      run: |
        node bin/cml-publish imgs/dark_logo.png --md > report.md
        node bin/cml-send-comment report.md

