name: "Ideal workflow"

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]

    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3

      - uses: iterative/setup-cml@v1

      - uses: actions/checkout@v2

      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.TEST_GITHUB_TOKEN }} 
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          cml-runner \
            --cloud-spot \
            --cloud azure \
            --cloud-region eastus \
            --cloud-type Standard_NC6 \
            --labels cml-runner-az-gpu

  test_machine_az:
    needs: check-container
    runs-on: [self-hosted,cml-runner-az-gpu]
    steps:
    - name: "tests"
      run: |
        nvidia-smi

  test_container_az:
    needs: check-container
    runs-on: [self-hosted,cml-runner-az-gpu]
    container:
      image: docker://dvcorg/cml
      options: --gpus all
    steps:
    - name: "tests"
      run: |
        nvidia-smi
